# Static configuration file for Floorlight project.
# Adjust the parameters below as needed.

pwm:
  frequency: 200 # Frequency in Hz

led:
  T_ramp_max: 2 # Ramp time in seconds, when using the full range of duty cycle (0-100%)
